### ISSUE TITLE
Inserting same entries changes the order of insertion

### ISSUE THREAD

**Issue by zapirkon** [sgodwincs/ordered-multimap-rs#21]
## Bug description

I can't see how to update existing entries other than inserting existing keys.
I used the insert function, since based on the description would either insert or replace a value:
> If the key is already in the multimap, the insertion ordering of the keys will remain unchanged.

But, with that function, the order of the list changes - it moves existing keys to the bottom.

- Would you like to work on a fix? [n]
  - maybe it can be done via `get_mut` or `get_all_mut`, not sure

## To Reproduce

1. In `test_list_ordered_multimap_keys` add
```
    assert_eq!(
      format!("{map:?}"),
      r#"{"key2": "value2", "key1": "value3", "key3": "value4"}"#
    );
```

## Expected behavior

```
    assert_eq!(
      format!("{map:?}"),
      r#"{"key1": "value3", "key2": "value2", "key3": "value4"}"#
    );
```

## Environment

- ordered-multimap version: [0.6.0]

**Comment by sgodwincs** [comment]
I believe `insert` is working as intended. It doesn't change the order of the keys as can be seen by the `test_list_ordered_multimap_keys` test assertions, but the order of the values does change. The documentation only says the keys will be remain in order, not the values. As for your reproduction, the debug implementation of the map is based on the order of the values which is why it seems like the keys have been re-ordered when they have in fact not been. It's bit of an arbitrary choice whether the debug implementation should be based on the key ordering or values.
