### ISSUE TITLE
Compatibility with stable Rust

### ISSUE THREAD

**Issue by zonyitoo** [sgodwincs/ordered-multimap-rs#4]
Is it possible to sacrifice some performance to make this crate could be built with stable Rust?

**Comment by sgodwincs** [comment]
Closed in [f4688e4](https://github.com/sgodwincs/ordered-multimap-rs/commit/f4688e4beda06c50c3df3046aba1e000d0596887).

Turns out since the last refactoring where I had to switch to using the `hashbrown` dependency directly, I no longer need the nightly feature enabled. So performance should not be impacted (and actually should be better since I updated the dependency as well which includes some improvements).

**Comment by zonyitoo** [comment]
Hoping for a new release

**Comment by sgodwincs** [comment]
Just released 0.2.3.
